# GitHub Pages configuration
plugins:
  - jekyll-sitemap

# Include XML files and set proper handling
include:
  - sitemap.xml
  - robots.txt

# Serve XML files with proper content-type
defaults:
  - scope:
      path: "*.xml"
    values:
      layout: null
      sitemap: false

# Site settings
title: "First Casino Gambling"
description: "Your premier online gaming destination"
url: "https://luongtrinh3018u-crypto.github.io"
baseurl: "/First-Casino-Gambling"

# Ensure proper XML handling
permalink: pretty
markdown: kramdown
highlighter: rouge